services:
  db:
    image: timescale/timescaledb:latest-pg15
    container_name: stridex_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Ayaulym^2011
      - POSTGRES_DB=stridex
    ports:
      - "5433:5432"
    volumes:
      - stridex_db:/var/lib/postgresql/data

  n8n:
    image: n8nio/n8n:latest
    container_name: stridex_n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=secretpassword
      - N8N_ENCRYPTION_KEY=random_stridex_key_123
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  stridex_db:
  n8n_data:
